compatibility_date = "2024-12-30"
name = "worker-weekmeter-kv"
workers_dev = true
routes = ["https://kv.weekmeter.com/kv*", "https://kv.weekmeter.com/version*"]
vars = {}
main = "./index.ts"
minify = true
upload_source_maps = true
kv_namespaces = [
	{ binding = "kvStore", id = "ea51c1dbf88a4ee9b0176c23a3af797b", preview_id = "ea51c1dbf88a4ee9b0176c23a3af797b" },
]
[observability.logs]
enabled = true

[env.local]
routes = []
vars = { adminSecret = "YWRtaW46cGFzc3dvcmQ=" }
durable_objects.bindings = []
kv_namespaces = [
	{ binding = "kvStore", id = "abc", preview_id = "abc" },
]
r2_buckets = []

[dev]
host = "example.com"
port = 8787
