compatibility_date = "2024-12-30"
name = "worker-kv-manager"
workers_dev = true
routes = ["https://api.example.com/kv*", "https://api.example.com/version/kv*"]
vars = {}
main = "./index.ts"
minify = true
upload_source_maps = true
kv_namespaces = [
	{ binding = "kvStore", id = "abc", preview_id = "abc" },
]
[observability.logs]
enabled = true

[env.local]
routes = []
vars = { adminSecret = "YWRtaW46cGFzc3dvcmQ=" }
durable_objects.bindings = []
kv_namespaces = [
	{ binding = "kvStore", id = "abc", preview_id = "abc" },
]
r2_buckets = []

[dev]
host = "example.com"
port = 8787
